apiVersion: v1
kind: Service
metadata:
  name: config-service-service
  labels:
    app: config-service-service
spec:
  selector:
    app: config-service-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer