apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-deployment
  labels:
    app: eureka-service-deployment
spec:
  selector:
    matchLabels:
      app: eureka-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service-deployment
    spec:
      containers:
        - name: eureka-service
          image: aldo564/kubernetes-eureka-service
          ports:
            - containerPort: 8761