apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
  labels:
    app: gateway-service-service
spec:
  selector:
    app: gateway-service-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer