apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: gateway-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service-deployment
    spec:
      containers:
        - name: gateway-service
          image: aldo564/kubernetes-gateway-service
          ports:
            - containerPort: 8080