apiVersion: apps/v1
kind: Deployment
metadata:
  name: porcentaje-deployment
  labels:
    app: porcentaje-deployment
spec:
  selector:
    matchLabels:
      app: porcentaje-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: porcentaje-deployment
    spec:
      containers:
        - name: porcentaje
          image: aldo564/kubernetes-porcentaje
          ports:
            - containerPort: 8086