apiVersion: v1
kind: Service
metadata:
  name: acopio-service
  labels:
    app: acopio-service
spec:
  selector:
    app: acopio-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer