apiVersion: v1
kind: Service
metadata:
  name: porcentaje-service
  labels:
    app: porcentaje-service
spec:
  selector:
    app: porcentaje-deployment
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer