apiVersion: v1
kind: Service
metadata:
  name: proveedor-service
  labels:
    app: proveedor-service
spec:
  selector:
    app: proveedor-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer