apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedor-deployment
  labels:
    app: proveedor-deployment
spec:
  selector:
    matchLabels:
      app: proveedor-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: proveedor-deployment
    spec:
      containers:
        - name: proveedor
          image: aldo564/kubernetes-proveedor
          ports:
            - containerPort: 8085