server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Aldo564/Lab_mingeso_2_2023
          search-paths: config-data
  application:
    name: config-service